# Generated by Django 6.0.3 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rendezvous_user_alter_rendezvous_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='type',
            field=models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('VISIO', 'À distance')], default='PRESENTIEL', max_length=20),
        ),
    ]
