# Generated by Django 6.0.5 on 2026-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rendezvous_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='visio_access_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='visio_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='visio_room_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
