# Generated by Django 6.0.5 on 2026-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rendezvous_visio_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PROPOSE', 'Proposé par secrétaire'), ('PATIENT_ACCEPTE', 'Patient a accepté'), ('PATIENT_REFUSE', 'Patient a refusé'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
