# Generated by Django 6.0.3 on 2026-04-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptomes', models.TextField()),
                ('diagnostic', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('pathologies_probables', models.JSONField(blank=True, null=True)),
                ('score_confiance', models.FloatField(blank=True, null=True)),
                ('rendezvous', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.rendezvous')),
            ],
        ),
    ]
