# Generated by Django 6.0.4 on 2026-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_consultation'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='date',
            new_name='date_consultation',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='pathologies_probables',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='score_confiance',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
