# Generated by Django 6.0.3 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
