# Generated by Django 6.0.4 on 2026-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
