# Generated by Django 6.0.4 on 2026-05-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdraft',
            name='patient_officiel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_origine', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientdraft',
            name='status',
            field=models.CharField(choices=[('ACTIF', 'Actif - En attente de 1ère visite'), ('CONVERTI', 'Converti - Patient officiel créé'), ('ABANDONNE', 'Abandonné - RDV manqué')], default='ACTIF', max_length=20),
        ),
        migrations.AddField(
            model_name='patientdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
