# Generated by Django 6.0.5 on 2026-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Cabinet Médical MedPredict', max_length=200)),
                ('telephone', models.CharField(default='+212 5 22 45 67 89', max_length=50)),
                ('email', models.EmailField(default='contact@medpredict.ma', max_length=254)),
                ('adresse', models.CharField(default="75 Boulevard d'Anfa, Casablanca, Maroc", max_length=300)),
                ('ouverture', models.CharField(default='08:30', max_length=5)),
                ('fermeture', models.CharField(default='18:00', max_length=5)),
                ('pause_debut', models.CharField(default='12:30', max_length=5)),
                ('pause_fin', models.CharField(default='14:00', max_length=5)),
                ('duree_rdv', models.CharField(default='30', max_length=5)),
                ('max_rdv_par_jour', models.CharField(default='20', max_length=5)),
                ('delai_min_heures', models.CharField(default='24', max_length=5)),
                ('type_defaut', models.CharField(default='CABINET', max_length=20)),
                ('medecin_nom', models.CharField(default='Dr. Mohamed Alami', max_length=150)),
                ('medecin_specialite', models.CharField(default='Médecine Générale & IA Diagnostique', max_length=150)),
                ('rpps', models.CharField(default='10100458923', max_length=50)),
                ('inpe', models.CharField(default='045892361', max_length=50)),
                ('pied_page', models.TextField(default='Document confidentiel généré par le système intelligent MedPredict.')),
            ],
            options={
                'verbose_name': 'Configuration Cabinet',
                'verbose_name_plural': 'Configuration Cabinet',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField()),
            ],
            options={
                'verbose_name': "Modèle d'Email",
                'verbose_name_plural': "Modèles d'Emails",
            },
        ),
    ]
