# Generated by Django 6.0.5 on 2026-05-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cabinetconfig_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_name',
            field=models.CharField(default='avatar1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(default='predefined', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
