# Generated by Django 6.0.5 on 2026-05-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_avatar_name_user_avatar_type_user_photo_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_type',
        ),
    ]
